apiVersion: apps/v1
kind: Deployment
metadata:
  name: gks-backend-deployment
  labels:
    app: gks-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gks-backend
  template:
    metadata:
      labels:
        app: gks-backend
    spec:
      containers:
      - name: api
        image: gks-fitness-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
            name: gks-fitness-secrets

---
apiVersion: v1
kind: Service
metadata:
  name: gks-backend-service
spec:
  type: NodePort
  selector:
    app: gks-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30050